version: '3.8'

services:
  mysql:
    image: mysql:8.0
    container_name: mysql_db
    restart: always
    environment:
      MYSQL_DATABASE: ${DB_NAME}
      MYSQL_USER: ${DB_USER}
      MYSQL_PASSWORD: ${DB_PASSWORD}
      MYSQL_ROOT_PASSWORD: ${DB_ROOT_PASSWORD}
    ports:
      - "${DB_PORT_MAPPED}:${DB_PORT_INTERNAL}"
    volumes:
      - mysql-data:/var/lib/mysql

  rabbitmq:
    image: rabbitmq:3.11-management-alpine
    container_name: rabbitmq_server
    restart: always
    ports:
      - "5672:5672"
      - "15672:15672"
    environment:
      - RABBITMQ_DEFAULT_USER=guest
      - RABBITMQ_DEFAULT_PASS=guest

  translation-api:
    build:
      context: ./translation-api
    container_name: translation_api
    restart: always
    ports:
      - "${API_PORT}:${API_PORT}"
    environment:
      - PORT=${API_PORT}
      - DB_HOST=${DB_HOST}
      - DB_USER=${DB_USER}
      - DB_PASSWORD=${DB_PASSWORD}
      - DB_NAME=${DB_NAME}
      - RABBITMQ_URL=${RABBITMQ_URL}
      - QUEUE_NAME=${QUEUE_NAME}
    depends_on:
      - mysql
      - rabbitmq

  translation-worker:
    build:
      context: ./translation-worker
    container_name: translation_worker
    restart: always
    environment:
      - DB_HOST=${DB_HOST}
      - DB_USER=${DB_USER}
      - DB_PASSWORD=${DB_PASSWORD}
      - DB_NAME=${DB_NAME}
      - RABBITMQ_URL=${RABBITMQ_URL}
      - QUEUE_NAME=${QUEUE_NAME}
      - DEEPL_API_KEY=${DEEPL_API_KEY}
    depends_on:
      - mysql
      - rabbitmq

volumes:
  mysql-data:
